version: '3.8'

services:
  redis:
    image: "redis:latest"
    container_name: "my_redis"
    ports:
      - "6379:6379"
    networks:
      - app_network

  postgres:
    image: "postgres:latest"
    container_name: "my_postgres"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  fastify_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "my_fastify_app"
    environment:

      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: mydatabase
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - postgres
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local